#!/bin/bash

# ==============================================================================
# Whites Castle POS - Commercial Release Packaging Pipeline
# Optimized for macOS/Linux (Bash 3.2+)
# ==============================================================================

# Exit immediately on error, uninitialized variables, or pipeline failures
set -euo pipefail

# --- Color Definitions for Premium Terminal Feedback ---
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}======================================================================${NC}"
echo -e "${CYAN}🏰 WHITES CASTLE POS: COMMERCIAL RELEASE BUILD SYSTEM${NC}"
echo -e "${CYAN}======================================================================${NC}"

# --- Step 1: Initialize Timestamp & Directory Name ---
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
STAGING_DIR="WhitesCastle_POS_Release_${TIMESTAMP}"
ZIP_NAME="WhitesCastle_POS_Release.zip"

echo -e "🚀 Preparing workspace..."
echo -e "   Staging Directory: ${YELLOW}${STAGING_DIR}${NC}"

# Ensure staging directory is completely fresh
if [ -d "$STAGING_DIR" ]; then
  echo -e "   ${YELLOW}Found existing staging folder, removing...${NC}"
  rm -rf "$STAGING_DIR"
fi
mkdir -p "$STAGING_DIR"

# --- Step 2: Selective Production Copy (Allowlist Approach) ---
echo -e "📂 Executing selective copy to exclude development bloat..."

# List of single files to copy directly
FILES_TO_COPY=(
  "docker-compose.yml"
  "Dockerfile"
  "package.json"
  "package-lock.json"
  "tsconfig.json"
  "vite.config.ts"
  "tailwind.config.js"
  "postcss.config.js"
  "index.html"
  "server.ts"
  "metadata.json"
)

for file in "${FILES_TO_COPY[@]}"; do
  if [ -f "$file" ]; then
    cp "$file" "$STAGING_DIR/"
    echo -e "   [✓] Copied file: ${GREEN}${file}${NC}"
  else
    echo -e "   [!] Warning: Direct file ${YELLOW}${file}${NC} not found. Skipping."
  fi
done

# Copy src directory
if [ -d "src" ]; then
  cp -R "src" "$STAGING_DIR/"
  echo -e "   [✓] Copied directory recursively: ${GREEN}src/${NC}"
else
  echo -e "   ${RED}[Error] Source directory 'src' is missing! Aborting build.${NC}"
  exit 1
fi

# Copy prisma schema without local sqlite db (dev.db)
mkdir -p "$STAGING_DIR/prisma"
if [ -f "prisma/schema.prisma" ]; then
  cp "prisma/schema.prisma" "$STAGING_DIR/prisma/"
  echo -e "   [✓] Copied production database definition: ${GREEN}prisma/schema.prisma${NC}"
else
  echo -e "   ${RED}[Error] prisma/schema.prisma is missing! Aborting build.${NC}"
  exit 1
fi

# Copy scripts directory (contains backup, restore, etc.)
mkdir -p "$STAGING_DIR/scripts"
if [ -d "scripts" ]; then
  cp -R scripts/* "$STAGING_DIR/scripts/"
  echo -e "   [✓] Copied script utilities recursively: ${GREEN}scripts/${NC}"
else
  echo -e "   ${YELLOW}[!] Warning: 'scripts' directory not found. Creating empty destination folder.${NC}"
fi

# Make sure utility scripts have executable flags
if [ -d "$STAGING_DIR/scripts" ]; then
  chmod +x "$STAGING_DIR/scripts"/*.sh 2>/dev/null || true
fi

# --- Step 3: Generate Strict Production-Ready .env.example ---
echo -e "📝 Generating clean, enterprise-ready .env.example template..."
cat << 'EOF' > "$STAGING_DIR/.env.example"
# ==============================================================================
# Whites Castle POS - Production Environment Configuration
# ==============================================================================

# --- Server Deployment Settings ---
NODE_ENV=production
PORT=3000

# --- Database Integration (Prisma URL) ---
# Replace with the path to your production PostgreSQL or SQLite storage
DATABASE_URL="file:./prisma/production.db"

# --- Security & Licensing Key Matrix ---
# LICENSE_SECRET: Must match the generator signature token
# HARDWARE_MAC: The hardware physical address of the primary POS terminal
# LICENSE_KEY: The cryptographically signed license key generated by support
LICENSE_SECRET=SUPER_SECRET_ENTERPRISE_KEY_9981
HARDWARE_MAC=00:1B:44:11:3A:B7
LICENSE_KEY=

# --- Gemini AI Integration ---
# Provide your server-side Google Gemini developer API key
GEMINI_API_KEY=
EOF
echo -e "   [✓] Created environment blueprint: ${GREEN}.env.example${NC}"

# --- Step 4: Strict Exclusions (Clean up any hidden dev files) ---
echo -e "🧼 Executing blacklist sweep for hidden development artifacts..."

# Clean macOS metadata and any temporary local caches in the staging directory
find "$STAGING_DIR" -name ".DS_Store" -depth -exec rm -f {} \;
find "$STAGING_DIR" -name ".git" -type d -prune -exec rm -rf {} \;
find "$STAGING_DIR" -name "node_modules" -type d -prune -exec rm -rf {} \;
find "$STAGING_DIR" -name ".env*" ! -name ".env.example" -type f -exec rm -f {} \;
find "$STAGING_DIR" -name "*.db" -type f -exec rm -f {} \;

echo -e "   [✓] Blacklist sweep complete. Node_modules, local secrets, and meta files scrubbed."

# --- Step 5: Compression into Archive ---
echo -e "📦 Packing application into compressed production deliverable..."

# Remove old zip if it exists to avoid conflicts
if [ -f "$ZIP_NAME" ]; then
  rm -f "$ZIP_NAME"
fi

# Check if zip command is available, fall back to tar if necessary
if command -v zip >/dev/null 2>&1; then
  zip -r "$ZIP_NAME" "$STAGING_DIR" > /dev/null
  echo -e "   [✓] Staging directory compressed with ${GREEN}ZIP${NC} successfully."
else
  echo -e "   ${YELLOW}[!] zip utility not found. Falling back to tar.gz...${NC}"
  ZIP_NAME="WhitesCastle_POS_Release.tar.gz"
  tar -czf "$ZIP_NAME" "$STAGING_DIR"
  echo -e "   [✓] Staging directory compressed with ${GREEN}TAR GZ${NC} successfully."
fi

# --- Step 6: Cleanup Staging Directory ---
echo -e "🧹 Sweeping temporary build workspace..."
rm -rf "$STAGING_DIR"
echo -e "   [✓] Workspace directory cleaned."

# --- Step 7: Release Reporting ---
FILE_SIZE="Unknown"
if [[ "$OSTYPE" == "darwin"* ]]; then
  FILE_SIZE=$(stat -f%z "$ZIP_NAME" | awk '{printf "%.2f MB", $1/1024/1024}')
else
  FILE_SIZE=$(stat -c%s "$ZIP_NAME" | awk '{printf "%.2f MB", $1/1024/1024}')
fi
ABSOLUTE_PATH=$(cd "$(dirname "$ZIP_NAME")" && pwd)/$ZIP_NAME

echo -e "${GREEN}======================================================================${NC}"
echo -e "${GREEN}🎉 COMMERCIAL RELEASE PACKAGED SUCCESSFULLY!${NC}"
echo -e "${GREEN}======================================================================${NC}"
echo -e "📦 Package Name:  ${CYAN}${ZIP_NAME}${NC}"
echo -e "🎚️  File Size:    ${CYAN}${FILE_SIZE}${NC}"
echo -e "📍 Absolute Path: ${YELLOW}${ABSOLUTE_PATH}${NC}"
echo -e "${GREEN}======================================================================${NC}"
echo -e "The release is optimized, clean, and ready for commercial delivery."
